### ISSUE TITLE
AccountScopeMismatchError after an error

### ISSUE THREAD

**Issue by marcelo-soto** [envato/double_entry#115]
Hi!,
I'm getting this error:

```
DoubleEntry::AccountScopeMismatchError (Expected instance of `User`, received instance of `User`)
```

every time I made an error in a method using DoubleEntry (even if the error is not DoubleEntry related). This happens in the console and the server, and the only solution is killing the server, restarting the console, and killing Spring.
I'm still using DoubleEntry in development, but I'm very afraid that the issue will cause a lot of trouble in production. Even using this https://github.com/envato/double_entry/issues/75#issuecomment-67241069 the issue remains.

Here's a more detailed example:
(everything works fine, on purpose delete a comma in a Hash)

```
SyntaxError (app/controllers/cartolas_controller.rb:16: syntax error, unexpected tIDENTIFIER, expecting ')'
...eEntry.account(:cilindros scope: x)}}
...                               ^
app/controllers/cartolas_controller.rb:23: syntax error, unexpected keyword_end, expecting '}'
app/controllers/cartolas_controller.rb:57: syntax error, unexpected keyword_end, expecting '}'):
  app/controllers/cartolas_controller.rb:16: syntax error, unexpected tIDENTIFIER, expecting ')'
  app/controllers/cartolas_controller.rb:23: syntax error, unexpected keyword_end, expecting '}'
  app/controllers/cartolas_controller.rb:57: syntax error, unexpected keyword_end, expecting '}'


  Rendered /Users/marcelo/.rvm/gems/ruby-2.2-head@bo_distribuidores/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_source.erb (5.4ms)
  Rendered /Users/marcelo/.rvm/gems/ruby-2.2-head@bo_distribuidores/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_trace.html.erb (2.5ms)
  Rendered /Users/marcelo/.rvm/gems/ruby-2.2-head@bo_distribuidores/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_request_and_response.html.erb (1.3ms)
  Rendered /Users/marcelo/.rvm/gems/ruby-2.2-head@bo_distribuidores/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/_web_console.html.erb (1.0ms)
  Rendered /Users/marcelo/.rvm/gems/ruby-2.2-head@bo_distribuidores/gems/web-console-2.0.0/lib/action_dispatch/templates/rescues/diagnostics.html.erb within rescues/layout (171.4ms)
```

Fixing the error, making the same request:

```
Started GET "/cartolas" for 127.0.0.1 at 2016-05-06 11:27:06 -0400
Processing by CartolasController#index as HTML
[...]
DoubleEntry::AccountScopeMismatchError (Expected instance of `User`, received instance of `User`):
  app/controllers/cartolas_controller.rb:13:in `block in index'
  app/controllers/cartolas_controller.rb:13:in `index'
```

Only restarting the servers everything is back to normal.

Please help me!!!

**Comment by doncote** [comment]
This same thing is happening to us.  Would love to find a solution.

**Comment by marcelo-soto** [comment]
Hi @doncote !, considering I posted this issue about 2 months ago and still don't have  a _formal_ solution, this is what I did:

in `application_controller.rb`

```
before_action :reload_accounts

...

  def reload_accounts
    DoubleEntry.configure do |config|
      config.accounts = nil
      config.transfers = nil
    end
    load "#{Rails.root.to_s}/config/initializers/double_entry.rb"
  end
```

I know it's ugly, slow and IDK if it's going to work in production, but I prefer that to restart the server.

**Comment by doncote** [comment]
I think we're going to fork the branch and pass strings instead of constants in the config and then constantize them when they're used.  Will submit a pull req if we can nail it down.

**Comment by KelseyDH** [comment]
I have a `User` and `Customer` model, and User delegates to customer.  I suspect this, or the existence of `Transfer` and `Account` models in my app is causing issues in normal scoping.

E.g. with a configuration using:

```
require 'double_entry'

DoubleEntry.configure do |config|
  config.define_accounts do |accounts|
    user_scope = accounts.active_record_scope_identifier(User)
    accounts.define(:identifier => :savings,  :scope_identifier => user_scope, :positive_only => true)
    accounts.define(:identifier => :checking, :scope_identifier => user_scope)
  end

  config.define_transfers do |transfers|
    transfers.define(:from => :checking, :to => :savings,  :code => :deposit)
    transfers.define(:from => :savings,  :to => :checking, :code => :withdraw)
  end
end
```

I get this error:

```
[1] > account = DoubleEntry.account(:checking, :scope => User.first)
  User Load (2.4ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
/Users/username/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/double_entry-1.0.1/lib/double_entry/account.rb:71: warning: constant ::Fixnum is deprecated
DoubleEntry::AccountScopeMismatchError: Expected instance of `Customer`, received instance of `User`
from /Users/username/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/double_entry-1.0.1/lib/double_entry/account.rb:74:in `block in scope_identifier'
```

Which can be fixed with using `User.first.id.to_s` instead as suggested:  

```
[2] > account = DoubleEntry.account(:checking, :scope => User.first.id.to_s)
  User Load (0.6ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
#{Account account: checking scope: 137 currency: USD}
```

However sadly, it appears that @marcelo-soto's hack for this doesn't fix the issue I'm having, as running in console:

```
> DoubleEntry.configure do |config|
      config.accounts = nil
      config.transfers = nil
    end
  > load "#{Rails.root.to_s}/config/initializers/double_entry.rb"
```

still gives back:

```
> account = DoubleEntry.account(:checking, :scope => User.first)
  User Load (0.3ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1  [["LIMIT", 1]]
DoubleEntry::AccountScopeMismatchError: Expected instance of `Customer`, received instance of `User`
from /Users/kelsey/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/double_entry-1.0.1/lib/double_entry/account.rb:74:in `block in scope_identifier'
```

**Comment by KelseyDH** [comment]
@marcelo-soto   Is it possible this class level instance memoizing is causing the configuration to look stale?

E.g. this line:
```
  module Configurable
    def self.included(base) #:nodoc:
      base.extend(ClassMethods)
    end

    module ClassMethods #:nodoc:
      def configuration
        @configuration ||= self::Configuration.new
      end

      def configure
        yield(configuration)
      end
    end
  end
```

When the code comment for it was based on a Thoughtbot article that gave this example:

```
module Clearance
  class << self
    attr_accessor :configuration
  end

  def self.configure
    self.configuration ||= Configuration.new
    yield(configuration)
  end

  class Configuration
    attr_accessor :mailer_sender

    def initialize
      @mailer_sender = 'donotreply@example.com'
    end
  end
end
```

With  `self.configuration ||= Configuration.new` being different from `@configuration ||= self::Configuration.new` ?!  Unsure, but just a thought.

**Comment by orien** [comment]
Given the problems this `active_record_scope_identifier` method is causing, I propose to just delete it. In its place we can use a simple block:
```ruby
user_scope = lambda do |user|
  raise 'account must be scoped by "User"' unless user.class.name == 'User'
  user.id
end
accounts.define(identifier: :savings,  scope_identifier: user_scope)
```
